name: Build/release

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest,linux-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          echo start install dependencies
          yarn install --network-timeout 100000

      - name: build main and render
        run: |
          echo build main and render
          yarn build

      - name: Package Electron app
        run: |
          echo Package Electron app
          yarn release


