name: Build/release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          echo start install dependencies
          yarn install --network-timeout 100000

      - name: Build project
        run: |
          echo start build project
          yarn build

      - name: Package Electron app
        run: |
          echo Package Electron app
          yarn package

      - name: Release
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          target_branch: release
          build_dir: release/app
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
