name: Build/Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: |
          echo start install dependencies
          yarn install --network-timeout 100000

      - name: Build main and render
        run: |
          echo build main and render
          yarn build

      - name: Package electron app
        run: |
          echo Package Electron app
          yarn release

      - name: Upload app installer
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.TOKEN }}
          files: |
            release/build/*.dmg
            release/build/*.zip
            release/build/*.exe
            release/build/*.blockmap

