name: Build/release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          echo start install dependencies
          yarn install --network-timeout 100000

      - name: Build project
        run: |
          echo start build project
          yarn build

      - name: Package Electron app
        run: |
          echo Package Electron app
          yarn package

      - name: Deploy to Staging server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SOURCE: "release/app/"
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: "root"
          TARGET: "/web/Matex"

