name: Build/release

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest, windows-latest ]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v2.4.0
        with:
          node-version: '14.x'

      - name: install dependencies
        run: |
          echo start install dependencies
          yarn install --network-timeout 100000

      - name: Build project
        run: |
          echo start build project
          yarn build

      - name: Package Electron app
        run: |
          echo Package Electron app
          yarn package

      - name: deploy file
        uses: wlixcc/SFTP-Deploy-Action@v1.0
        with:
          username: 'root'
          server: ${{ secrets.HOST }}
          ssh_private_key: ${{ secrets.PRIVATE_KEY }}
          local_path: './release/app/*'
          remote_path: '/web/Matex'
          args: '-o ConnectTimeout=5'

